#version 450

layout(local_size_x = 16, local_size_y = 16) in;
layout(set = 0, binding = 5, rgba8) writeonly uniform image2D outputImage;
layout(set = 0, binding = 0) uniform sampler2D samp;
layout(set = 0, binding = 2) uniform sampler2DArray history;
layout(set = 0, binding = 1, std140) uniform SpriteExtended {
    vec4 mouse;
    vec4 u0;
    vec4 u1;
    vec4 u2;
    vec4 u3;
    vec4 custom_uniforms[16];
    vec4 audio_bands;
    vec4 audio_history;
} ext;

#define time_f ext.u2.y
#define amp_l ext.audio_bands.x

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    if (any(greaterThanEqual(pixel, size))) return;
    vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
    vec4 live_frame = textureLod(samp, uv, 0.0);
    float bounce_speed = 0.5;
    float ping_pong = abs(fract(time_f * bounce_speed) * 2.0 - 1.0); 
    float max_stretch = 0.5 + (amp_l * 0.5); 
    float stretch_amount = ping_pong * max_stretch;
    float scale_x = 1.0 / (1.0 + stretch_amount);
    vec2 stretch_uv = vec2(uv.x * scale_x, uv.y);
    vec4 stretch_pixel = textureLod(samp, stretch_uv, 0.0);
    vec4 final_color = mix(live_frame, stretch_pixel, 0.5);
    imageStore(outputImage, pixel, final_color);
}