#!/usr/bin/env python3

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COMPUTE_DIR = ROOT / "compute"

FILTERS = [
    ("Blank", "Blank", "color", "Black output"),
    ("Negate", "Negate", "color", "RGB inversion"),
    ("Grayscale", "Grayscale", "color", "Luma grayscale"),
    ("Darken", "Darken", "color", "Adjustable darkening"),
    ("DarkNegate", "DarkNegate", "color", "Dark inverted color"),
    ("GammaDarken5", "GammaDarken5", "color", "Moderate gamma darkening"),
    ("GammaDarken10", "GammaDarken10", "color", "Strong gamma darkening"),
    ("All Red", "AllRed", "channel", "Red-channel isolation"),
    ("All Green", "AllGreen", "channel", "Green-channel isolation"),
    ("All Blue", "AllBlue", "channel", "Blue-channel isolation"),
    ("ColorOrderSwap", "ColorOrderSwap", "channel", "Fixed RGB permutation"),
    ("ColorOrderSwapMap", "ColorOrderSwapMap", "channel", "Animated RGB permutation"),
    ("FlipX_Axis", "FlipX_Axis", "geometry", "Horizontal flip"),
    ("FlipY_Axis", "FlipY_Axis", "geometry", "Vertical flip"),
    ("FlipBoth", "FlipBoth", "geometry", "Horizontal and vertical flip"),
    ("Sideways Mirror", "SidewaysMirror", "geometry", "Outward horizontal mirror"),
    ("Mirror No Blend", "MirrorNoBlend", "geometry", "Inward horizontal mirror"),
    ("FlipBlendW", "FlipBlendW", "geometry", "Horizontal flip blend"),
    ("FlipBlendH", "FlipBlendH", "geometry", "Vertical flip blend"),
    ("FlipBlendWH", "FlipBlendWH", "geometry", "Dual-axis flip blend"),
    ("RGB Shift", "RGBShift", "channel", "Separated red and blue sampling"),
    ("RGB Sep", "RGBSep", "channel", "Adjustable RGB separation"),
    ("Scanlines", "Scanlines", "line", "Alternating dark scanlines"),
    ("InvertedScanlines", "InvertedScanlines", "line", "Alternating inverted scanlines"),
    ("BlendedScanLines", "BlendedScanLines", "line", "Neighbor-blended scanlines"),
    ("ScanlineBlack", "ScanlineBlack", "line", "Hard black scanlines"),
    ("PixelatedSquare", "PixelatedSquare", "pixelate", "Small square pixelation"),
    ("PixelateBlock", "PixelateBlock", "pixelate", "Six-pixel block sampling"),
    ("PixelateNoResize8", "PixelateNoResize8", "pixelate", "Eight-pixel block sampling"),
    ("PixelateNoResize12", "PixelateNoResize12", "pixelate", "Twelve-pixel block sampling"),
    ("PixelateNoResize16", "PixelateNoResize16", "pixelate", "Sixteen-pixel block sampling"),
    ("PixelateNoResize24", "PixelateNoResize24", "pixelate", "Twenty-four-pixel block sampling"),
    ("PixelateNoResize32", "PixelateNoResize32", "pixelate", "Thirty-two-pixel block sampling"),
    ("PixelateRect", "PixelateRect", "pixelate", "Adjustable rectangular pixelation"),
    ("Block", "Block", "block", "Source and block-color blend"),
    ("BlockXor", "BlockXor", "block", "Block-sampled byte XOR"),
    ("BlockScale", "BlockScale", "block", "Scaled block byte color"),
    ("BlockStrobe", "BlockStrobe", "block", "Animated inverted blocks"),
    ("Bitwise_XOR", "Bitwise_XOR", "bitwise", "Byte XOR with adjustable mask"),
    ("Bitwise_AND", "Bitwise_AND", "bitwise", "Byte AND with adjustable mask"),
    ("Bitwise_OR", "Bitwise_OR", "bitwise", "Byte OR with adjustable mask"),
    ("Bitwise_Rotate", "BitwiseRotate", "bitwise", "Eight-bit channel rotation"),
    ("Bitwise_Rotate Diff", "BitwiseRotateDiff", "bitwise", "XOR with rotated channel bits"),
    ("BitwiseXorScale", "BitwiseXorScale", "bitwise", "XOR with scaled byte channels"),
    ("GradientRGB", "GradientRGB", "gradient", "RGB coordinate gradient modulation"),
    ("GradientLeftRight", "GradientLeftRight", "gradient", "Horizontal animated gradient"),
    ("GradientDown", "GradientDown", "gradient", "Vertical gradient modulation"),
    ("GradientColors", "GradientColors", "gradient", "Animated cosine palette"),
    ("Threshold", "Threshold", "threshold", "Per-channel threshold"),
    ("ThresholdDark", "ThresholdDark", "threshold", "Luma dark-threshold removal"),
    ("Flash Black", "FlashBlack", "strobe", "Alternating source and black"),
    ("FlashWhite", "FlashWhite", "strobe", "Alternating source and white"),
    ("FlashBlackAndWhite", "FlashBlackAndWhite", "strobe", "Black-and-white flash"),
    ("Strobe Red Then Green Then Blue", "StrobeRedGreenBlue", "strobe", "Cycling isolated RGB channels"),
    ("RGBFlash", "RGBFlash", "strobe", "Animated RGB color flash"),
    ("StrobeScan", "StrobeScan", "strobe", "Moving luminous scan band"),
    ("NegativeStrobe", "NegativeStrobe", "strobe", "Source and negative strobe"),
    ("BrightStrobe", "BrightStrobe", "strobe", "Brightness strobe"),
    ("DarkStrobe", "DarkStrobe", "strobe", "Darkness strobe"),
    ("HalfNegateStrobe", "HalfNegateStrobe", "strobe", "Moving partial negative"),
    ("FadeStrobe", "FadeStrobe", "strobe", "Smooth source-to-negative fade"),
    ("MirrorStrobe", "MirrorStrobe", "strobe", "Alternating source and mirror"),
    ("AndStrobe", "AndStrobe", "strobe", "Animated byte AND mask"),
    ("OrStrobe", "OrStrobe", "strobe", "Animated byte OR mask"),
    ("RandomStrobeFlash", "RandomStrobeFlash", "strobe", "Frame-seeded negative flashes"),
    ("ScaleFlash", "ScaleFlash", "strobe", "Animated center zoom"),
    ("ColorFlashIncrease", "ColorFlashIncrease", "strobe", "Additive animated color flash"),
    ("Wave", "Wave", "distort", "Horizontal sine displacement"),
    ("HighWave", "HighWave", "distort", "High-amplitude sine displacement"),
    ("Double Vision", "DoubleVision", "distort", "Symmetric offset blend"),
    ("SlideRGB", "SlideRGB", "distort", "Multi-axis RGB displacement"),
    ("Side2Side", "Side2Side", "distort", "Animated horizontal slide"),
    ("Top2Bottom", "Top2Bottom", "distort", "Animated vertical slide"),
    ("Outward", "Outward", "distort", "Animated center expansion"),
    ("Outward Square", "OutwardSquare", "distort", "Square-distance expansion"),
    ("ShiftPixels", "ShiftPixels", "distort", "Row-band horizontal displacement"),
    ("ShiftPixelsDown", "ShiftPixelsDown", "distort", "Column-band vertical displacement"),
    ("DiagonalLines", "DiagonalLines", "line", "Animated diagonal line modulation"),
    ("HorizontalLines", "HorizontalLines", "line", "Animated horizontal line modulation"),
    ("Lines", "Lines", "line", "Crossed animated line modulation"),
    ("WhiteLines", "WhiteLines", "line", "Thin white line overlay"),
    ("ThickWhiteLines", "ThickWhiteLines", "line", "Thick white line overlay"),
    ("GradientLines", "GradientLines", "gradient", "Rainbow diagonal gradient lines"),
    ("GradientSelf", "GradientSelf", "gradient", "Horizontal self-gradient"),
    ("GradientSelfVertical", "GradientSelfVertical", "gradient", "Vertical self-gradient"),
    ("GradientStripes", "GradientStripes", "gradient", "Animated color stripes"),
    ("GradientReverse", "GradientReverse", "gradient", "Reverse horizontal gradient"),
    ("GradientReverseVertical", "GradientReverseVertical", "gradient", "Reverse vertical gradient"),
    ("GradientReverseBox", "GradientReverseBox", "gradient", "Repeated box gradient"),
    ("GradientNewFilter", "GradientNewFilter", "gradient", "Animated palette modulation"),
    ("GradientLeftRightInOut", "GradientLeftRightInOut", "gradient", "Centered horizontal gradient"),
    ("GradientUpDownInOut", "GradientUpDownInOut", "gradient", "Centered vertical gradient"),
    ("SquareBars", "SquareBars", "grid", "Alternating square bar sampling"),
    ("SquareBars8", "SquareBars8", "grid", "Eight-pixel square bars"),
    ("SquareVertical8", "SquareVertical8", "grid", "Eight-pixel vertical mirror bars"),
    ("SquareVertical16", "SquareVertical16", "grid", "Sixteen-pixel vertical mirror bars"),
    ("GridFilter8x", "GridFilter8x", "grid", "Eight-pixel grid sampling"),
    ("GridFilter16x", "GridFilter16x", "grid", "Sixteen-pixel grid sampling"),
    ("GridFilter8xBlend", "GridFilter8xBlend", "grid", "Blended eight-pixel grid"),
    ("Circular", "Circular", "distort", "Polar circular distortion"),
    ("Self AlphaBlend", "SelfAlphaBlend", "blend", "Adjustable nearby-pixel self blend"),
    ("Self Scale", "SelfScale", "color", "Wrapped byte-channel scaling"),
    ("Blend #3", "Blend3", "blend", "Source and dual-flip average"),
    ("MirrorBlend", "MirrorBlend", "mirror", "Adjustable horizontal mirror blend"),
    ("Mirror Average", "MirrorAverage", "mirror", "Horizontal mirror average"),
    ("Mirror Average Mix", "MirrorAverageMix", "mirror", "Source and dual-mirror mix"),
    ("MoveRed", "MoveRed", "channel", "Animated red-channel displacement"),
    ("MoveRGB", "MoveRGB", "channel", "Animated three-channel displacement"),
    ("MoveRedGreenBlue", "MoveRedGreenBlue", "channel", "Diagonal RGB displacement"),
    ("HorizontalBlend", "HorizontalBlend", "blend", "Horizontal neighbor blend"),
    ("VerticalBlend", "VerticalBlend", "blend", "Vertical neighbor blend"),
    ("OppositeBlend", "OppositeBlend", "blend", "Opposite-coordinate blend"),
    ("Soft_Mirror", "Soft_Mirror", "mirror", "Edge-weighted mirror"),
    ("ColorMorphing", "ColorMorphing", "color", "Animated source-driven palette"),
    ("LineRGB", "LineRGB", "channel", "RGB channel line bands"),
    ("PixelRGB", "PixelRGB", "channel", "RGB channel pixel pattern"),
    ("BoxedRGB", "BoxedRGB", "channel", "RGB channel block pattern"),
    ("ColorRange", "ColorRange", "color", "Adjustable color quantization"),
    ("InterMirror", "InterMirror", "mirror", "Interlaced horizontal mirror"),
    ("InterFullMirror", "InterFullMirror", "mirror", "Checkerboard dual-axis mirror"),
    ("MirrorRGB", "MirrorRGB", "mirror", "Mirror-separated RGB channels"),
    ("AverageVertical", "AverageVertical", "blend", "Three-sample vertical average"),
    ("RGBMirror", "RGBMirror", "mirror", "RGB dual-axis mirror"),
    ("RandomXorOpposite", "RandomXorOpposite", "bitwise", "Seeded opposite-pixel XOR"),
    ("RandomMirror", "RandomMirror", "mirror", "Frame-selected mirror axis"),
    ("RandomMirrorBlend", "RandomMirrorBlend", "mirror", "Adjustable random-axis mirror blend"),
    ("RandomMirrorAlphaBlend", "RandomMirrorAlphaBlend", "mirror", "Seeded random mirror alpha"),
    ("MirrorXor", "MirrorXor", "bitwise", "Source and horizontal-mirror XOR"),
    ("MirrorXorAll", "MirrorXorAll", "bitwise", "Source and dual-mirror XOR"),
    ("MirrorXorScale", "MirrorXorScale", "bitwise", "Scaled mirror byte XOR"),
    ("EnergyMirror", "EnergyMirror", "mirror", "Amplified mirror difference"),
    ("MirrorXorAlpha", "MirrorXorAlpha", "bitwise", "Alpha blend with mirror XOR"),
    ("FlipMirror", "FlipMirror", "mirror", "Split-axis mirror"),
    ("FlipMirrorAverage", "FlipMirrorAverage", "mirror", "Average of source and axis mirrors"),
    ("AlphaBlendWithSource", "AlphaBlendWithSource", "blend", "Adjustable scaled-source blend"),
    ("RGBMirror1", "RGBMirror1", "mirror", "Reordered mirrored RGB channels"),
    ("FlashMirror", "FlashMirror", "mirror", "Mirror negative flash"),
    ("ReverseMirrorX", "ReverseMirrorX", "mirror", "Reverse folded mirror"),
    ("MirrorXorAll_Reverse", "MirrorXorAll_Reverse", "bitwise", "Reverse all-mirror XOR"),
    ("MirrorRGBReverse", "MirrorRGBReverse", "mirror", "Reverse mirrored channels"),
    ("MirrorRGBReverseBlend", "MirrorRGBReverseBlend", "mirror", "Reverse mirror channel blend"),
    ("MirrorBitwiseXor", "MirrorBitwiseXor", "bitwise", "Rotated-bit mirror XOR"),
    ("AlphaBlendMirror", "AlphaBlendMirror", "mirror", "Dual-mirror alpha blend"),
    ("TwistedMirror", "TwistedMirror", "mirror", "Polar twisted mirror"),
    ("FlipAlphaBlend", "FlipAlphaBlend", "blend", "Animated axis-flip blend"),
    ("MirrorMedian", "MirrorMedian", "mirror", "Mirror and horizontal-neighbor median"),
    ("MirrorAlphaBlend", "MirrorAlphaBlend", "mirror", "Source and dual-mirror blend"),
    ("MirrorEachSecond", "MirrorEachSecond", "mirror", "Timeline-selected mirror mode"),
    ("Mirror_Xor_Combined", "Mirror_Xor_Combined", "bitwise", "Combined mirror average XOR"),
    ("MirrorVerticalAndHorizontal", "MirrorVerticalAndHorizontal", "mirror", "Four-way mirror average"),
    ("Tri", "Tri", "geometry", "Animated triangular color geometry"),
    ("Distort", "Distort", "distort", "Two-axis sine distortion"),
    ("CosSinMultiply", "cossinMultiply", "color", "Cosine and sine color modulation"),
    ("Pixel Scale", "pixelScale", "pixelate", "Animated pixel-block scaling"),
    ("Boxes", "Boxes", "grid", "Adjustable box grid"),
    ("Boxes Fade", "BoxesFade", "grid", "Animated fading box grid"),
    ("WhitePixel", "WhitePixel", "pixelate", "Sparse animated white pixels"),
    ("FourSquare", "FourSquare", "geometry", "Four-way tiled reflection"),
    ("EightSquare", "EightSquare", "geometry", "Eight-way tiled reflection"),
    ("DiagonalSquare", "DiagonalSquare", "geometry", "Diagonal square displacement"),
    ("DiagonalSquareRandom", "DiagonalSquareRandom", "geometry", "Random diagonal square displacement"),
    ("SquareStretchDown", "SquareStretchDown", "distort", "Downward square-band stretch"),
    ("SquareStretchRight", "SquareStretchRight", "distort", "Rightward square-band stretch"),
    ("SquareStretchUp", "SquareStretchUp", "distort", "Upward square-band stretch"),
    ("SquareStretchLeft", "SquareStretchLeft", "distort", "Leftward square-band stretch"),
    ("RandomQuads", "RandomQuads", "geometry", "Seeded quadrant transforms"),
    ("GridRandom", "GridRandom", "grid", "Seeded grid-cell displacement"),
    ("GridRandomPixel", "GridRandomPixel", "grid", "Seeded grid pixel replacement"),
    ("Curtain", "Curtain", "distort", "Horizontal curtain folds"),
    ("RandomCurtain", "RandomCurtain", "distort", "Random horizontal curtain folds"),
    ("CurtainVertical", "CurtainVertical", "distort", "Vertical curtain folds"),
    ("RandomCurtainVertical", "RandomCurtainVertical", "distort", "Random vertical curtain folds"),
    ("SlideFilter", "SlideFilter", "distort", "Alternating horizontal slides"),
    ("SlideFilterXor", "SlideFilterXor", "bitwise", "Horizontal slide byte XOR"),
    ("RandomSlideFilter", "RandomSlideFilter", "distort", "Seeded horizontal slides"),
    ("SlideUpDown", "SlideUpDown", "distort", "Alternating vertical slides"),
    ("SlideUpDownXor", "SlideUpDownXor", "bitwise", "Vertical slide byte XOR"),
    ("SlideUpDownRandom", "SlideUpDownRandom", "distort", "Seeded vertical slides"),
    ("StretchOutward", "StretchOutward", "distort", "Animated outward stretch"),
    ("ExpandFrame", "ExpandFrame", "distort", "Animated frame expansion"),
    ("RotateFrame", "RotateFrame", "geometry", "Continuous frame rotation"),
    ("RotateFrameReverse", "RotateFrameReverse", "geometry", "Reverse frame rotation"),
    ("RotateSet", "RotateSet", "geometry", "Stepped frame rotation"),
    ("RotateSetReverse", "RotateSetReverse", "geometry", "Reverse stepped rotation"),
    ("PixelateExpandDistort", "PixelateExpandDistort", "pixelate", "Pixelated radial expansion"),
    ("PixelateExpandDistortX", "PixelateExpandDistortX", "pixelate", "Pixelated horizontal expansion"),
    ("PixelateExpandDistortY", "PixelateExpandDistortY", "pixelate", "Pixelated vertical expansion"),
    ("PixelateExpandDistortExtra", "PixelateExpandDistortExtra", "pixelate", "Layered pixel expansion distortion"),
    ("DistortPixelate", "DistortPixelate", "pixelate", "Wave-distorted pixelation"),
    ("PixelateSquares", "PixelateSquares", "pixelate", "Checker-scaled square pixelation"),
    ("DiagPixel", "DiagPixel", "distort", "Diagonal pixel displacement"),
    ("DiagPixelY", "DiagPixelY", "distort", "Vertical diagonal displacement"),
    ("DiagPixelY2", "DiagPixelY2", "distort", "Alternating vertical diagonal displacement"),
    ("DiagPixelY3", "DiagPixelY3", "distort", "Layered vertical diagonal displacement"),
    ("DiagPixelY4", "DiagPixelY4", "distort", "RGB vertical diagonal displacement"),
    ("DiagSquare", "DiagSquare", "geometry", "Diagonal square-band sampling"),
    ("DiagSquareLarge", "DiagSquareLarge", "geometry", "Large diagonal square-band sampling"),
    ("ExpandLeftRight", "ExpandLeftRight", "distort", "Horizontal center expansion"),
    ("ShiftPixelsRGB", "ShiftPixelsRGB", "channel", "Independent RGB pixel shifts"),
    ("JaggedLine", "JaggedLine", "distort", "Seeded jagged line displacement"),
    ("ScratchyTrails", "ScratchyTrails", "trail", "Scratch-like offset color trails"),
    ("ExpandPixelate", "ExpandPixelate", "pixelate", "Expanding pixel blocks"),
    ("DiagSquare8", "DiagSquare8", "geometry", "Eight-pixel diagonal squares"),
    ("DiagSquareRandom", "DiagSquareRandom", "geometry", "Seeded diagonal square shifts"),
    ("DiagSquareX", "DiagSquareX", "geometry", "Crossed diagonal square shifts"),
    ("SquareShiftDirRGB", "SquareShiftDirRGB", "channel", "Directional square RGB shifts"),
    ("StretchLineRowIncRGB", "StretchLineRowIncRGB", "channel", "Increasing row RGB stretch"),
    ("StretchLineColIncRGB", "StretchLineColIncRGB", "channel", "Increasing column RGB stretch"),
    ("StretchLineRowIncSource", "StretchLineRowIncSource", "distort", "Increasing source row stretch"),
    ("StretchLineColIncSource", "StretchLineColIncSource", "distort", "Increasing source column stretch"),
    ("AlternateAlpha", "AlternateAlpha", "blend", "Alternating source alpha modulation"),
    ("Square_Block_Resize_Vertical_RGB", "Square_Block_Resize_Vertical_RGB", "channel", "Vertical block RGB resize"),
    ("DiagSquareRGB", "DiagSquareRGB", "channel", "Diagonal square RGB separation"),
    ("Square_Block_Resize_RGB", "Square_Block_Resize_RGB", "channel", "Square block RGB resize"),
    ("VariableLinesY_RGB", "VariableLinesY_RGB", "channel", "Variable vertical RGB lines"),
    ("SquareShiftDirGradient", "SquareShiftDirGradient", "gradient", "Directional square gradient shifts"),
    ("BlendWithSourcePercent", "BlendWithSourcePercent", "blend", "Animated source percentage blend"),
    ("ReverseRandom", "ReverseRandom", "geometry", "Seeded random reversal"),
    ("SquareBlockGlitch", "SquareBlockGlitch", "glitch", "Seeded square block glitch"),
    ("SquareStretchRows", "SquareStretchRows", "distort", "Alternating stretched rows"),
    ("SquareStretchRowsDelay", "SquareStretchRowsDelay", "distort", "Delayed stretched rows"),
    ("SquareStretchEven", "SquareStretchEven", "distort", "Even-band square stretch"),
    ("SketchFilter", "SketchFilter", "edge", "Monochrome sketch edges"),
    ("SquareStretchEven32", "SquareStretchEven32", "distort", "Wide even-band square stretch"),
    ("RGBLineFuzz", "RGBLineFuzz", "channel", "Vertical RGB line fuzz"),
    ("RGBLineFuzzX", "RGBLineFuzzX", "channel", "Horizontal RGB line fuzz"),
    ("LinesAcrossX", "LinesAcrossX", "line", "Animated lines across rows"),
    ("XorLineX", "XorLineX", "bitwise", "Row line byte XOR"),
    ("AlphaComponentIncrease", "AlphaComponentIncrease", "color", "Animated component amplification"),
    ("ExpandContract", "ExpandContract", "distort", "Alternating expansion and contraction"),
    ("MoveInThenMoveOut", "MoveInThenMoveOut", "distort", "Slow inward and outward motion"),
    ("MoveInThenMoveOutFast", "MoveInThenMoveOutFast", "distort", "Fast inward and outward motion"),
    ("DistortionFuzz", "DistortionFuzz", "glitch", "Seeded two-axis distortion fuzz"),
    ("DistortionByRow", "DistortionByRow", "distort", "Progressive row distortion"),
    ("DistortionByRowRev", "DistortionByRowRev", "distort", "Reverse progressive row distortion"),
    ("DistortionByRowVar", "DistortionByRowVar", "distort", "Oscillating row distortion"),
    ("DistortionByRowRand", "DistortionByRowRand", "distort", "Seeded row distortion"),
    ("DistortionByCol", "DistortionByCol", "distort", "Progressive column distortion"),
    ("DistortionByColRand", "DistortionByColRand", "distort", "Seeded column distortion"),
    ("DistortionByColVar", "DistortionByColVar", "distort", "Oscillating column distortion"),
    ("LongLines", "LongLines", "line", "Long displaced horizontal lines"),
    ("TearRight", "TearRight", "glitch", "Rightward image tearing"),
    ("TearDown", "TearDown", "glitch", "Downward image tearing"),
    ("TearUp", "TearUp", "glitch", "Upward image tearing"),
    ("TearLeft", "TearLeft", "glitch", "Leftward image tearing"),
    ("DistortStretch", "DistortStretch", "distort", "Layered stretch distortion"),
    ("FadeOnOff", "FadeOnOff", "strobe", "Smooth fade on and off"),
    ("Stereo", "Stereo", "channel", "Stereo red-cyan separation"),
    ("ShiftLinesDown", "ShiftLinesDown", "distort", "Downward shifted line bands"),
    ("VisualSnow", "VisualSnow", "noise", "Animated monochrome visual snow"),
    ("VisualSnowX2", "VisualSnowX2", "noise", "Dense animated color snow"),
    ("LineGlitch", "LineGlitch", "glitch", "Seeded horizontal line glitch"),
    ("SlitReverse64", "SlitReverse64", "geometry", "Reversed sixty-four-pixel slits"),
    ("SlitReverse64_Increase", "SlitReverse64_Increase", "geometry", "Expanding reversed slits"),
    ("SlitStretch", "SlitStretch", "distort", "Animated slit stretching"),
    ("LineLeftRight", "LineLeftRight", "distort", "Alternating left-right lines"),
    ("LineLeftRightResize", "LineLeftRightResize", "distort", "Resized alternating line shifts"),
    ("RGBLineTrails", "RGBLineTrails", "trail", "Separated RGB line trails"),
    ("RGBCollectionBlend", "RGBCollectionBlend", "trail", "Offset RGB trail blend"),
    ("RGBCollectionIncrease", "RGBCollectionIncrease", "trail", "Increasing RGB trail separation"),
    ("RGBCollectionEx", "RGBCollectionEx", "trail", "Extended RGB trail blend"),
    ("RGBLongTrails", "RGBLongTrails", "trail", "Long RGB displacement trails"),
    ("FadeRGB_Speed", "FadeRGB_Speed", "color", "Speed-controlled RGB fading"),
    ("RGBStrobeTrails", "RGBStrobeTrails", "trail", "Strobing RGB trails"),
    ("FadeRGB_Variable", "FadeRGB_Variable", "color", "Variable RGB channel fading"),
    ("BoxGlitch", "BoxGlitch", "glitch", "Seeded box displacement glitch"),
    ("VerticalPictureDistort", "VerticalPictureDistort", "distort", "Vertical picture distortion"),
    ("ShortTrail", "ShortTrail", "trail", "Short directional trail"),
    ("DiagInward", "DiagInward", "geometry", "Diagonal inward sampling"),
    ("DiagSquareInward", "DiagSquareInward", "geometry", "Inward diagonal squares"),
    ("DiagSquareInwardResize", "DiagSquareInwardResize", "geometry", "Resized inward diagonal squares"),
    ("DiagSquareInwardResizeXY", "DiagSquareInwardResizeXY", "geometry", "Two-axis resized inward squares"),
    ("ParticleSlide", "ParticleSlide", "glitch", "Particle-like sliding blocks"),
    ("DiagPixelated", "DiagPixelated", "pixelate", "Diagonal pixelation"),
    ("DiagPixelatedResize", "DiagPixelatedResize", "pixelate", "Resized diagonal pixelation"),
    ("DiagPixelRGB_Collection", "DiagPixelRGB_Collection", "channel", "Diagonal RGB pixel trails"),
    ("RGBShiftTrails", "RGBShiftTrails", "trail", "Animated RGB shift trails"),
    ("PictureShiftDown", "PictureShiftDown", "distort", "Downward picture shift"),
    ("PictureShiftRight", "PictureShiftRight", "distort", "Rightward picture shift"),
    ("PictureShiftDownRight", "PictureShiftDownRight", "distort", "Diagonal picture shift"),
    ("FlipPictureShift", "FlipPictureShift", "geometry", "Flipped picture shifting"),
    ("FlipPictureRandomMirror", "FlipPictureRandomMirror", "geometry", "Random flipped mirror"),
    ("PictureShiftVariable", "PictureShiftVariable", "distort", "Variable picture shifting"),
    ("RGBWideTrails", "RGBWideTrails", "trail", "Wide RGB displacement trails"),
    ("StretchR_Right", "StretchR_Right", "channel", "Rightward red stretch"),
    ("StretchG_Right", "StretchG_Right", "channel", "Rightward green stretch"),
    ("StretchB_Right", "StretchB_Right", "channel", "Rightward blue stretch"),
    ("StretchR_Down", "StretchR_Down", "channel", "Downward red stretch"),
    ("StretchG_Down", "StretchG_Down", "channel", "Downward green stretch"),
    ("StretchB_Down", "StretchB_Down", "channel", "Downward blue stretch"),
    ("Distorted_LinesY", "Distorted_LinesY", "line", "Distorted vertical lines"),
    ("Distorted_LinesX", "Distorted_LinesX", "line", "Distorted horizontal lines"),
    ("TripHSV", "TripHSV", "color", "Animated HSV color trip"),
    ("Diag_Line_InOut", "Diag_Line_InOut", "distort", "Diagonal line expansion and contraction"),
    ("Histogram", "Histogram", "color", "Histogram-style tonal mapping"),
    ("XorSumStrobe", "XorSumStrobe", "bitwise", "Summed-channel XOR strobe"),
    ("DetectEdges", "DetectEdges", "edge", "Luma edge detection"),
    ("SobelNorm", "SobelNorm", "edge", "Normalized Sobel edges"),
    ("SobelThreshold", "SobelThreshold", "edge", "Thresholded Sobel edges"),
    ("MedianBlurHigherLevel", "MedianBlurHigherLevel", "blur", "High-radius median-like blur"),
    ("FadeBars", "FadeBars", "line", "Animated fading horizontal bars"),
    ("StrobeXor", "StrobeXor", "bitwise", "Animated full-frame XOR strobe"),
    ("IntertwinedMirror", "IntertwinedMirror", "mirror", "Intertwined horizontal mirror bands"),
    ("InterRGB_Bars_XY", "InterRGB_Bars_XY", "channel", "Interlaced RGB bars on both axes"),
    ("InterRGB_Bars_X", "InterRGB_Bars_X", "channel", "Interlaced horizontal RGB bars"),
    ("InterRGB_Bars_Y", "InterRGB_Bars_Y", "channel", "Interlaced vertical RGB bars"),
    ("FlipBlendAll", "FlipBlendAll", "mirror", "Animated blend of all flipped orientations"),
    ("SelfScaleXorIncrease", "SelfScaleXorIncrease", "bitwise", "Animated scaled-color XOR"),
    ("Blend_RedGreenBlue", "Blend_RedGreenBlue", "channel", "Neighbor-sampled RGB blend"),
    ("XorBlend_RedGreenBlue", "XorBlend_RedGreenBlue", "bitwise", "Neighbor-sampled RGB XOR"),
    ("BlendIncrease_RedGreenBlue", "BlendIncrease_RedGreenBlue", "channel", "Expanding RGB separation blend"),
    ("Blend_RedReenBlue_Dark", "Blend_RedReenBlue_Dark", "channel", "Dark RGB separation blend"),
    ("DarkModBlend", "DarkModBlend", "color", "Animated dark modulo blend"),
    ("PictureBuzz", "PictureBuzz", "glitch", "Rapid horizontal picture buzz"),
    ("IncDifference", "IncDifference", "color", "Animated channel difference"),
    ("IncDifferenceAlpha", "IncDifferenceAlpha", "color", "Alpha-blended animated difference"),
    ("ChannelSort_NoBlend_Descending", "ChannelSort_NoBlend_Descending", "channel", "Descending per-pixel channel sort"),
    ("ChannelSort_NoBlend_Ascending", "ChannelSort_NoBlend_Ascending", "channel", "Ascending per-pixel channel sort"),
    ("RandomPixels", "RandomPixels", "noise", "Seeded random bright pixels"),
    ("DarkRandomPixels", "DarkRandomPixels", "noise", "Seeded random dark pixels"),
    ("Bars", "Bars", "line", "Animated alternating color bars"),
    ("BlendCombinedValues", "BlendCombinedValues", "blend", "Combined neighboring pixel blend"),
    ("GradientXorPixels", "GradientXorPixels", "bitwise", "Coordinate-gradient pixel XOR"),
    ("PurpleRain", "PurpleRain", "color", "Animated purple rain streaks"),
    ("PixelByPixelXor", "PixelByPixelXor", "bitwise", "Coordinate-driven per-pixel XOR"),
    ("CopyXorAlpha", "CopyXorAlpha", "bitwise", "Offset-copy XOR alpha blend"),
    ("AveragePixelsXor", "AveragePixelsXor", "bitwise", "Averaged neighborhood XOR"),
    ("AveragePixelAlpha", "AveragePixelAlpha", "blend", "Cross-neighborhood alpha average"),
    ("NegativeByRow", "NegativeByRow", "line", "Alternating negative rows"),
    ("IncorrectLine", "IncorrectLine", "glitch", "Misaligned horizontal glitch lines"),
    ("XorShift", "XorShift", "bitwise", "Animated shifted-pixel XOR"),
    ("StrobeXorAndOr", "StrobeXorAndOr", "bitwise", "Cycling XOR, AND, and OR strobe"),
    ("XorWithSource", "XorWithSource", "bitwise", "Source color XOR pattern"),
    ("RGBSep1x", "RGBSep1x", "channel", "One-axis animated RGB separation"),
    ("RandomIncrease", "RandomIncrease", "noise", "Random channel amplification"),
    ("DivideAndIncH", "DivideAndIncH", "geometry", "Horizontally divided channel increase"),
    ("DivideAndIncW", "DivideAndIncW", "geometry", "Vertically divided channel increase"),
    ("IncreaseDecreaseGamma", "IncreaseDecreaseGamma", "color", "Oscillating gamma adjustment"),
    ("GammaIncDecIncrease", "GammaIncDecIncrease", "color", "Increasing gamma oscillation"),
    ("TwistedVision", "TwistedVision", "distort", "Twisted radial channel vision"),
    ("RandomFlipFilter", "RandomFlipFilter", "geometry", "Timeline-seeded random flip"),
    ("NegParadox", "NegParadox", "color", "Oscillating negative color paradox"),
    ("ThoughtMode", "ThoughtMode", "color", "Animated high-contrast thought palette"),
    ("RainbowBlend", "rainbowBlend", "color", "Animated rainbow color blend"),
    ("RandBlend", "randBlend", "noise", "Seeded random color blend"),
    ("NewBlend", "newBlend", "color", "Animated nonlinear color blend"),
    ("ShuffleColorMap", "ShuffleColorMap", "channel", "Timeline-shuffled channel mapping"),
    ("XorSquare", "XorSquare", "bitwise", "Checker-square color XOR"),
    ("AverageHorizontalFilter", "AverageHorizontalFilter", "blend", "Horizontal neighborhood average"),
    ("AverageVerticalFilter", "AverageVerticalFilter", "blend", "Vertical neighborhood average"),
]


def shader_name(display_name):
    value = re.sub(r"[^a-z0-9]+", "_", display_name.lower()).strip("_")
    return f"{value}.comp"


def write_shader(effect_id, display_name):
    path = COMPUTE_DIR / shader_name(display_name)
    path.write_text(
        "#version 450\n"
        f"#define AC_EFFECT_ID {effect_id}\n"
        '#include "include/filter_common.glsl"\n',
        encoding="utf-8",
    )
    return path.relative_to(ROOT).as_posix()


def main():
    COMPUTE_DIR.mkdir(parents=True, exist_ok=True)
    shader_paths = [
        write_shader(effect_id, item[0])
        for effect_id, item in enumerate(FILTERS)
    ]
    manifest = {
        "version": 1,
        "backend": "acmxvk",
        "library_type": "source",
        "custom_uniforms": {
            "amount": {"slot": 0, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 0.5},
            "scale_value": {"slot": 1, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 0.5},
            "speed": {"slot": 2, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 0.5},
            "mix_amount": {"slot": 3, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 1.0},
        },
        "shaders": shader_paths,
    }
    (ROOT / "library.json").write_text(
        json.dumps(manifest, indent=4) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
