#!/usr/bin/env python3

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COMPUTE_DIR = ROOT / "compute"

FILTERS = [
    ("Blank", "Blank", "color", "Black output"),
    ("Negate", "Negate", "color", "RGB inversion"),
    ("Grayscale", "Grayscale", "color", "Luma grayscale"),
    ("Darken", "Darken", "color", "Adjustable darkening"),
    ("DarkNegate", "DarkNegate", "color", "Dark inverted color"),
    ("GammaDarken5", "GammaDarken5", "color", "Moderate gamma darkening"),
    ("GammaDarken10", "GammaDarken10", "color", "Strong gamma darkening"),
    ("All Red", "AllRed", "channel", "Red-channel isolation"),
    ("All Green", "AllGreen", "channel", "Green-channel isolation"),
    ("All Blue", "AllBlue", "channel", "Blue-channel isolation"),
    ("ColorOrderSwap", "ColorOrderSwap", "channel", "Fixed RGB permutation"),
    ("ColorOrderSwapMap", "ColorOrderSwapMap", "channel", "Animated RGB permutation"),
    ("FlipX_Axis", "FlipX_Axis", "geometry", "Horizontal flip"),
    ("FlipY_Axis", "FlipY_Axis", "geometry", "Vertical flip"),
    ("FlipBoth", "FlipBoth", "geometry", "Horizontal and vertical flip"),
    ("Sideways Mirror", "SidewaysMirror", "geometry", "Outward horizontal mirror"),
    ("Mirror No Blend", "MirrorNoBlend", "geometry", "Inward horizontal mirror"),
    ("FlipBlendW", "FlipBlendW", "geometry", "Horizontal flip blend"),
    ("FlipBlendH", "FlipBlendH", "geometry", "Vertical flip blend"),
    ("FlipBlendWH", "FlipBlendWH", "geometry", "Dual-axis flip blend"),
    ("RGB Shift", "RGBShift", "channel", "Separated red and blue sampling"),
    ("RGB Sep", "RGBSep", "channel", "Adjustable RGB separation"),
    ("Scanlines", "Scanlines", "line", "Alternating dark scanlines"),
    ("InvertedScanlines", "InvertedScanlines", "line", "Alternating inverted scanlines"),
    ("BlendedScanLines", "BlendedScanLines", "line", "Neighbor-blended scanlines"),
    ("ScanlineBlack", "ScanlineBlack", "line", "Hard black scanlines"),
    ("PixelatedSquare", "PixelatedSquare", "pixelate", "Small square pixelation"),
    ("PixelateBlock", "PixelateBlock", "pixelate", "Six-pixel block sampling"),
    ("PixelateNoResize8", "PixelateNoResize8", "pixelate", "Eight-pixel block sampling"),
    ("PixelateNoResize12", "PixelateNoResize12", "pixelate", "Twelve-pixel block sampling"),
    ("PixelateNoResize16", "PixelateNoResize16", "pixelate", "Sixteen-pixel block sampling"),
    ("PixelateNoResize24", "PixelateNoResize24", "pixelate", "Twenty-four-pixel block sampling"),
    ("PixelateNoResize32", "PixelateNoResize32", "pixelate", "Thirty-two-pixel block sampling"),
    ("PixelateRect", "PixelateRect", "pixelate", "Adjustable rectangular pixelation"),
    ("Block", "Block", "block", "Source and block-color blend"),
    ("BlockXor", "BlockXor", "block", "Block-sampled byte XOR"),
    ("BlockScale", "BlockScale", "block", "Scaled block byte color"),
    ("BlockStrobe", "BlockStrobe", "block", "Animated inverted blocks"),
    ("Bitwise_XOR", "Bitwise_XOR", "bitwise", "Byte XOR with adjustable mask"),
    ("Bitwise_AND", "Bitwise_AND", "bitwise", "Byte AND with adjustable mask"),
    ("Bitwise_OR", "Bitwise_OR", "bitwise", "Byte OR with adjustable mask"),
    ("Bitwise_Rotate", "BitwiseRotate", "bitwise", "Eight-bit channel rotation"),
    ("Bitwise_Rotate Diff", "BitwiseRotateDiff", "bitwise", "XOR with rotated channel bits"),
    ("BitwiseXorScale", "BitwiseXorScale", "bitwise", "XOR with scaled byte channels"),
    ("GradientRGB", "GradientRGB", "gradient", "RGB coordinate gradient modulation"),
    ("GradientLeftRight", "GradientLeftRight", "gradient", "Horizontal animated gradient"),
    ("GradientDown", "GradientDown", "gradient", "Vertical gradient modulation"),
    ("GradientColors", "GradientColors", "gradient", "Animated cosine palette"),
    ("Threshold", "Threshold", "threshold", "Per-channel threshold"),
    ("ThresholdDark", "ThresholdDark", "threshold", "Luma dark-threshold removal"),
    ("Flash Black", "FlashBlack", "strobe", "Alternating source and black"),
    ("FlashWhite", "FlashWhite", "strobe", "Alternating source and white"),
    ("FlashBlackAndWhite", "FlashBlackAndWhite", "strobe", "Black-and-white flash"),
    ("Strobe Red Then Green Then Blue", "StrobeRedGreenBlue", "strobe", "Cycling isolated RGB channels"),
    ("RGBFlash", "RGBFlash", "strobe", "Animated RGB color flash"),
    ("StrobeScan", "StrobeScan", "strobe", "Moving luminous scan band"),
    ("NegativeStrobe", "NegativeStrobe", "strobe", "Source and negative strobe"),
    ("BrightStrobe", "BrightStrobe", "strobe", "Brightness strobe"),
    ("DarkStrobe", "DarkStrobe", "strobe", "Darkness strobe"),
    ("HalfNegateStrobe", "HalfNegateStrobe", "strobe", "Moving partial negative"),
    ("FadeStrobe", "FadeStrobe", "strobe", "Smooth source-to-negative fade"),
    ("MirrorStrobe", "MirrorStrobe", "strobe", "Alternating source and mirror"),
    ("AndStrobe", "AndStrobe", "strobe", "Animated byte AND mask"),
    ("OrStrobe", "OrStrobe", "strobe", "Animated byte OR mask"),
    ("RandomStrobeFlash", "RandomStrobeFlash", "strobe", "Frame-seeded negative flashes"),
    ("ScaleFlash", "ScaleFlash", "strobe", "Animated center zoom"),
    ("ColorFlashIncrease", "ColorFlashIncrease", "strobe", "Additive animated color flash"),
    ("Wave", "Wave", "distort", "Horizontal sine displacement"),
    ("HighWave", "HighWave", "distort", "High-amplitude sine displacement"),
    ("Double Vision", "DoubleVision", "distort", "Symmetric offset blend"),
    ("SlideRGB", "SlideRGB", "distort", "Multi-axis RGB displacement"),
    ("Side2Side", "Side2Side", "distort", "Animated horizontal slide"),
    ("Top2Bottom", "Top2Bottom", "distort", "Animated vertical slide"),
    ("Outward", "Outward", "distort", "Animated center expansion"),
    ("Outward Square", "OutwardSquare", "distort", "Square-distance expansion"),
    ("ShiftPixels", "ShiftPixels", "distort", "Row-band horizontal displacement"),
    ("ShiftPixelsDown", "ShiftPixelsDown", "distort", "Column-band vertical displacement"),
    ("DiagonalLines", "DiagonalLines", "line", "Animated diagonal line modulation"),
    ("HorizontalLines", "HorizontalLines", "line", "Animated horizontal line modulation"),
    ("Lines", "Lines", "line", "Crossed animated line modulation"),
    ("WhiteLines", "WhiteLines", "line", "Thin white line overlay"),
    ("ThickWhiteLines", "ThickWhiteLines", "line", "Thick white line overlay"),
    ("GradientLines", "GradientLines", "gradient", "Rainbow diagonal gradient lines"),
    ("GradientSelf", "GradientSelf", "gradient", "Horizontal self-gradient"),
    ("GradientSelfVertical", "GradientSelfVertical", "gradient", "Vertical self-gradient"),
    ("GradientStripes", "GradientStripes", "gradient", "Animated color stripes"),
    ("GradientReverse", "GradientReverse", "gradient", "Reverse horizontal gradient"),
    ("GradientReverseVertical", "GradientReverseVertical", "gradient", "Reverse vertical gradient"),
    ("GradientReverseBox", "GradientReverseBox", "gradient", "Repeated box gradient"),
    ("GradientNewFilter", "GradientNewFilter", "gradient", "Animated palette modulation"),
    ("GradientLeftRightInOut", "GradientLeftRightInOut", "gradient", "Centered horizontal gradient"),
    ("GradientUpDownInOut", "GradientUpDownInOut", "gradient", "Centered vertical gradient"),
    ("SquareBars", "SquareBars", "grid", "Alternating square bar sampling"),
    ("SquareBars8", "SquareBars8", "grid", "Eight-pixel square bars"),
    ("SquareVertical8", "SquareVertical8", "grid", "Eight-pixel vertical mirror bars"),
    ("SquareVertical16", "SquareVertical16", "grid", "Sixteen-pixel vertical mirror bars"),
    ("GridFilter8x", "GridFilter8x", "grid", "Eight-pixel grid sampling"),
    ("GridFilter16x", "GridFilter16x", "grid", "Sixteen-pixel grid sampling"),
    ("GridFilter8xBlend", "GridFilter8xBlend", "grid", "Blended eight-pixel grid"),
    ("Circular", "Circular", "distort", "Polar circular distortion"),
    ("Self AlphaBlend", "SelfAlphaBlend", "blend", "Adjustable nearby-pixel self blend"),
    ("Self Scale", "SelfScale", "color", "Wrapped byte-channel scaling"),
    ("Blend #3", "Blend3", "blend", "Source and dual-flip average"),
    ("MirrorBlend", "MirrorBlend", "mirror", "Adjustable horizontal mirror blend"),
    ("Mirror Average", "MirrorAverage", "mirror", "Horizontal mirror average"),
    ("Mirror Average Mix", "MirrorAverageMix", "mirror", "Source and dual-mirror mix"),
    ("MoveRed", "MoveRed", "channel", "Animated red-channel displacement"),
    ("MoveRGB", "MoveRGB", "channel", "Animated three-channel displacement"),
    ("MoveRedGreenBlue", "MoveRedGreenBlue", "channel", "Diagonal RGB displacement"),
    ("HorizontalBlend", "HorizontalBlend", "blend", "Horizontal neighbor blend"),
    ("VerticalBlend", "VerticalBlend", "blend", "Vertical neighbor blend"),
    ("OppositeBlend", "OppositeBlend", "blend", "Opposite-coordinate blend"),
    ("Soft_Mirror", "Soft_Mirror", "mirror", "Edge-weighted mirror"),
    ("ColorMorphing", "ColorMorphing", "color", "Animated source-driven palette"),
    ("LineRGB", "LineRGB", "channel", "RGB channel line bands"),
    ("PixelRGB", "PixelRGB", "channel", "RGB channel pixel pattern"),
    ("BoxedRGB", "BoxedRGB", "channel", "RGB channel block pattern"),
    ("ColorRange", "ColorRange", "color", "Adjustable color quantization"),
    ("InterMirror", "InterMirror", "mirror", "Interlaced horizontal mirror"),
    ("InterFullMirror", "InterFullMirror", "mirror", "Checkerboard dual-axis mirror"),
    ("MirrorRGB", "MirrorRGB", "mirror", "Mirror-separated RGB channels"),
    ("AverageVertical", "AverageVertical", "blend", "Three-sample vertical average"),
    ("RGBMirror", "RGBMirror", "mirror", "RGB dual-axis mirror"),
    ("RandomXorOpposite", "RandomXorOpposite", "bitwise", "Seeded opposite-pixel XOR"),
    ("RandomMirror", "RandomMirror", "mirror", "Frame-selected mirror axis"),
    ("RandomMirrorBlend", "RandomMirrorBlend", "mirror", "Adjustable random-axis mirror blend"),
    ("RandomMirrorAlphaBlend", "RandomMirrorAlphaBlend", "mirror", "Seeded random mirror alpha"),
    ("MirrorXor", "MirrorXor", "bitwise", "Source and horizontal-mirror XOR"),
    ("MirrorXorAll", "MirrorXorAll", "bitwise", "Source and dual-mirror XOR"),
    ("MirrorXorScale", "MirrorXorScale", "bitwise", "Scaled mirror byte XOR"),
    ("EnergyMirror", "EnergyMirror", "mirror", "Amplified mirror difference"),
    ("MirrorXorAlpha", "MirrorXorAlpha", "bitwise", "Alpha blend with mirror XOR"),
    ("FlipMirror", "FlipMirror", "mirror", "Split-axis mirror"),
    ("FlipMirrorAverage", "FlipMirrorAverage", "mirror", "Average of source and axis mirrors"),
    ("AlphaBlendWithSource", "AlphaBlendWithSource", "blend", "Adjustable scaled-source blend"),
    ("RGBMirror1", "RGBMirror1", "mirror", "Reordered mirrored RGB channels"),
    ("FlashMirror", "FlashMirror", "mirror", "Mirror negative flash"),
    ("ReverseMirrorX", "ReverseMirrorX", "mirror", "Reverse folded mirror"),
    ("MirrorXorAll_Reverse", "MirrorXorAll_Reverse", "bitwise", "Reverse all-mirror XOR"),
    ("MirrorRGBReverse", "MirrorRGBReverse", "mirror", "Reverse mirrored channels"),
    ("MirrorRGBReverseBlend", "MirrorRGBReverseBlend", "mirror", "Reverse mirror channel blend"),
    ("MirrorBitwiseXor", "MirrorBitwiseXor", "bitwise", "Rotated-bit mirror XOR"),
    ("AlphaBlendMirror", "AlphaBlendMirror", "mirror", "Dual-mirror alpha blend"),
    ("TwistedMirror", "TwistedMirror", "mirror", "Polar twisted mirror"),
    ("FlipAlphaBlend", "FlipAlphaBlend", "blend", "Animated axis-flip blend"),
    ("MirrorMedian", "MirrorMedian", "mirror", "Mirror and horizontal-neighbor median"),
    ("MirrorAlphaBlend", "MirrorAlphaBlend", "mirror", "Source and dual-mirror blend"),
    ("MirrorEachSecond", "MirrorEachSecond", "mirror", "Timeline-selected mirror mode"),
    ("Mirror_Xor_Combined", "Mirror_Xor_Combined", "bitwise", "Combined mirror average XOR"),
    ("MirrorVerticalAndHorizontal", "MirrorVerticalAndHorizontal", "mirror", "Four-way mirror average"),
    ("Tri", "Tri", "geometry", "Animated triangular color geometry"),
    ("Distort", "Distort", "distort", "Two-axis sine distortion"),
    ("CosSinMultiply", "cossinMultiply", "color", "Cosine and sine color modulation"),
    ("Pixel Scale", "pixelScale", "pixelate", "Animated pixel-block scaling"),
    ("Boxes", "Boxes", "grid", "Adjustable box grid"),
    ("Boxes Fade", "BoxesFade", "grid", "Animated fading box grid"),
    ("WhitePixel", "WhitePixel", "pixelate", "Sparse animated white pixels"),
    ("FourSquare", "FourSquare", "geometry", "Four-way tiled reflection"),
    ("EightSquare", "EightSquare", "geometry", "Eight-way tiled reflection"),
    ("DiagonalSquare", "DiagonalSquare", "geometry", "Diagonal square displacement"),
    ("DiagonalSquareRandom", "DiagonalSquareRandom", "geometry", "Random diagonal square displacement"),
    ("SquareStretchDown", "SquareStretchDown", "distort", "Downward square-band stretch"),
    ("SquareStretchRight", "SquareStretchRight", "distort", "Rightward square-band stretch"),
    ("SquareStretchUp", "SquareStretchUp", "distort", "Upward square-band stretch"),
    ("SquareStretchLeft", "SquareStretchLeft", "distort", "Leftward square-band stretch"),
    ("RandomQuads", "RandomQuads", "geometry", "Seeded quadrant transforms"),
    ("GridRandom", "GridRandom", "grid", "Seeded grid-cell displacement"),
    ("GridRandomPixel", "GridRandomPixel", "grid", "Seeded grid pixel replacement"),
    ("Curtain", "Curtain", "distort", "Horizontal curtain folds"),
    ("RandomCurtain", "RandomCurtain", "distort", "Random horizontal curtain folds"),
    ("CurtainVertical", "CurtainVertical", "distort", "Vertical curtain folds"),
    ("RandomCurtainVertical", "RandomCurtainVertical", "distort", "Random vertical curtain folds"),
    ("SlideFilter", "SlideFilter", "distort", "Alternating horizontal slides"),
    ("SlideFilterXor", "SlideFilterXor", "bitwise", "Horizontal slide byte XOR"),
    ("RandomSlideFilter", "RandomSlideFilter", "distort", "Seeded horizontal slides"),
    ("SlideUpDown", "SlideUpDown", "distort", "Alternating vertical slides"),
    ("SlideUpDownXor", "SlideUpDownXor", "bitwise", "Vertical slide byte XOR"),
    ("SlideUpDownRandom", "SlideUpDownRandom", "distort", "Seeded vertical slides"),
    ("StretchOutward", "StretchOutward", "distort", "Animated outward stretch"),
    ("ExpandFrame", "ExpandFrame", "distort", "Animated frame expansion"),
    ("RotateFrame", "RotateFrame", "geometry", "Continuous frame rotation"),
    ("RotateFrameReverse", "RotateFrameReverse", "geometry", "Reverse frame rotation"),
    ("RotateSet", "RotateSet", "geometry", "Stepped frame rotation"),
    ("RotateSetReverse", "RotateSetReverse", "geometry", "Reverse stepped rotation"),
    ("PixelateExpandDistort", "PixelateExpandDistort", "pixelate", "Pixelated radial expansion"),
    ("PixelateExpandDistortX", "PixelateExpandDistortX", "pixelate", "Pixelated horizontal expansion"),
    ("PixelateExpandDistortY", "PixelateExpandDistortY", "pixelate", "Pixelated vertical expansion"),
    ("PixelateExpandDistortExtra", "PixelateExpandDistortExtra", "pixelate", "Layered pixel expansion distortion"),
    ("DistortPixelate", "DistortPixelate", "pixelate", "Wave-distorted pixelation"),
    ("PixelateSquares", "PixelateSquares", "pixelate", "Checker-scaled square pixelation"),
    ("DiagPixel", "DiagPixel", "distort", "Diagonal pixel displacement"),
    ("DiagPixelY", "DiagPixelY", "distort", "Vertical diagonal displacement"),
    ("DiagPixelY2", "DiagPixelY2", "distort", "Alternating vertical diagonal displacement"),
    ("DiagPixelY3", "DiagPixelY3", "distort", "Layered vertical diagonal displacement"),
    ("DiagPixelY4", "DiagPixelY4", "distort", "RGB vertical diagonal displacement"),
    ("DiagSquare", "DiagSquare", "geometry", "Diagonal square-band sampling"),
    ("DiagSquareLarge", "DiagSquareLarge", "geometry", "Large diagonal square-band sampling"),
    ("ExpandLeftRight", "ExpandLeftRight", "distort", "Horizontal center expansion"),
    ("ShiftPixelsRGB", "ShiftPixelsRGB", "channel", "Independent RGB pixel shifts"),
    ("JaggedLine", "JaggedLine", "distort", "Seeded jagged line displacement"),
]


def shader_name(display_name):
    value = re.sub(r"[^a-z0-9]+", "_", display_name.lower()).strip("_")
    return f"{value}.comp"


def write_shader(effect_id, display_name):
    path = COMPUTE_DIR / shader_name(display_name)
    path.write_text(
        "#version 450\n"
        f"#define AC_EFFECT_ID {effect_id}\n"
        '#include "include/filter_common.glsl"\n',
        encoding="utf-8",
    )
    return path.relative_to(ROOT).as_posix()


def main():
    COMPUTE_DIR.mkdir(parents=True, exist_ok=True)
    shader_paths = [
        write_shader(effect_id, item[0])
        for effect_id, item in enumerate(FILTERS)
    ]
    manifest = {
        "version": 1,
        "backend": "acmxvk",
        "library_type": "source",
        "custom_uniforms": {
            "amount": {"slot": 0, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 0.5},
            "scale_value": {"slot": 1, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 0.5},
            "speed": {"slot": 2, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 0.5},
            "mix_amount": {"slot": 3, "minimum": 0.0, "maximum": 1.0, "step": 0.01, "value": 1.0},
        },
        "shaders": shader_paths,
    }
    (ROOT / "library.json").write_text(
        json.dumps(manifest, indent=4) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
